<?php

/**
*
* impletementing  our hooks
*/
/**
 *  Implementing hook_theme
*/
function module_princess_theme($existing, $type, $theme, $path){
	
	return [
		'princess_list'=>[
		    'variables'=> ['items' =>[], 'title'=>''],
		]
	];
}
/**
 *  Implementing hook_form
*/
function module_princess_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	if($form_id == 'node_article_form'){

		$form['field_tags']['#access'] = FALSE;
		$form['title']['widget'][0]['value']['#title'] = t('Viola Article Title');
       // kint($form);die();
	   $form['#validate'][] = '_module_p_articale_valid'; //create a function 
	}
}
/**
 * Our custom validation function.
 */
function _module_p_articale_valid($form,$form_state){
	if(is_numeric($form_state -> getValue('title')[0]['value'])){
           $form_state->setErrorByName('title',t('Title should not be a number!'));
	}
}
/**
 * impletment hook_entity_presave
 */

function module_princess_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
	if( $entity->bundle()=='article'){
	     // kint($entity);die();
		drupal_set_message(
			'We are resaving our article with name "'.$entity->get('title')-> getValue('title')[0]['value'].' "'
		);
	}
}